---

- name: Restart nginx
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: Restart kerberosio
  service:
    name: kerberosio
    enabled: yes
    state: restarted

- name: Reboot
  reboot:
    post_reboot_delay: 20
  when: allow_reboots == True

- name: Show allow_reboots
  debug: msg="Reboots allowed - {{ allow_reboots }}"