---
# Install Kerberos.io web

- name: Install Kerberos.io Web dependent packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nginx 
    - php7.1
    - php7.1-curl
    - php7.1-gd
    - php7.1-fpm
    - php7.1-cli
    - php7.1-opcache
    - php7.1-mbstring
    - php7.1-xml
    - php7.1-zip
    - php7.1-mcrypt
    - php7.1-readline